apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/deployment.yaml
  - resources/service.yaml
configMapGenerator:
  - name: duke-user-producer-service-configmap-env
    envs:
      - configs/config.env
  - name: duke-user-producer-service-configmap-file
    files:
      - configs/config.yaml
secretGenerator:
  - name: duke-user-producer-service-secret-env
    envs:
      - secrets/secret.env
